### ISSUE TITLE
SPHEREPACK download problem

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jswhit/pyspharm#3]
```
After trying to python setup.py install

WARNING: By downloading the SPHEREPACK source files, you are agreeing to
 the terms of the SPHEREPACK license at
 http://www2.cisl.ucar.edu/resources/legacy/spherepack/license

 Do you want to download SPHEREPACK now? (yes or no)yes

And error on handshaking

Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    urllib.urlretrieve(URL,tarfname)
  File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 437, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1176, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 8] _ssl.c:510: EOF occurred in violation 
of protocol
```

Original issue reported on code.google.com by `arnaldor...@gmail.com` on 15 May 2014 at 1:55

**Comment by DWesl** [comment]
Given pyspharm now vendors SpherePack in `src`, I think this is resolved.
